### ISSUE TITLE
Switch to Form Requests 

### ISSUE THREAD

**Issue by MagedAhmad** [SaidOmarDev/adminpanel#1]
instead of validating data inside controller
make it clean and switch validation to form requests 

check this link : 
https://laravel.com/docs/8.x/validation#creating-form-requests

https://github.com/SaidOmarDev/adminpanel/blob/c955a4ba5713985418b82488dc1c6b71798627aa/app/Http/Controllers/ClientController.php#L24

**Comment by SaidOmarDev** [comment]
I switch to form request now.
