### ISSUE TITLE
Standard issue

### ISSUE THREAD

**Issue by MagedAhmad** [SaidOmarDev/adminpanel#2]
before each (return ) you have to leave a blank line, unless the return is alone inside a statement-group (like an if statement)

try to get used to follow standard from now on, it would make it way easier later, and your could would look awesome. 

![image](https://user-images.githubusercontent.com/12874132/149610183-95d7ba5a-7694-4274-8239-17ff630869c5.png)

check this link : 
https://symfony.com/doc/current/contributing/code/standards.html

https://github.com/SaidOmarDev/adminpanel/blob/c955a4ba5713985418b82488dc1c6b71798627aa/app/Http/Controllers/ClientController.php#L14

**Comment by SaidOmarDev** [comment]
I resolve it now and use the standard.
