### ISSUE TITLE
Check anonymous migrations 

### ISSUE THREAD

**Issue by MagedAhmad** [SaidOmarDev/adminpanel#3]
There's nothing wrong with the current migration file, kudos to u ;) 

but you can check anonymous migrations 
https://laravel-news.com/laravel-anonymous-migrations

https://github.com/SaidOmarDev/adminpanel/blob/c955a4ba5713985418b82488dc1c6b71798627aa/database/migrations/2014_10_12_000000_create_users_table.php#L7

**Comment by SaidOmarDev** [comment]
I replaced the migration class name with anonymous migrations now.
